apiVersion: v1
kind: Pod
metadata:
  name: java-web-project
  annotations:
    ad.datadoghq.com/java-web-project.check_names: '["tomcat"]'
    ad.datadoghq.com/java-web-project.init_configs: '[{"is_jmx": "true", "collect_default_metrics": "true"}]'
    ad.datadoghq.com/java-web-project.instances: |
      [
        {
          "host": "%%host%%",
          "port": "7199"
        }
      ]
    ad.datadoghq.com/java-web-project.logs: '[{"source":"tomcat","service":"java-web-project"}]'
spec:
    containers:
    - name: java-web-project
      image: dogdemo/java_web_project:latest
      ports:
        - containerPort: 8080
          name: http
        - containerPort: 7199
          name: jmx
      env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
